# Alaska salmon data cleaning

This notebook holds the code to clean the Alaskan salmon dataset found on [KNB](https://knb.ecoinformatics.org/view/doi:10.5063/F1707ZTM). This data set spans 1922 to 2017 and contains salmon measurements, sample locations, and type of salmon capture. The final result is a local relational database that makes this data more usable. It can be recreated by following the steps from the Alaska salmon relational database repository.

In [ ]:
# import necessary libraries
import pandas as pd
import numpy as np
import os
import janitor

In [2]:
# load in data
salmon_data = pd.read_csv("Alaskan-salmon1922-2017/data/ASL_master.csv")
length_type = pd.read_csv("Alaskan-salmon1922-2017/data/length_type_lookup.csv")
location = pd.read_csv("Alaskan-salmon1922-2017/data/Locations_subdistricts_uniqueID.csv")
project_type = pd.read_csv("Alaskan-salmon1922-2017/data/ASLProjectType.csv")
gear =  pd.read_csv("Alaskan-salmon1922-2017/data/gear.csv")

/var/folders/kj/1ybgv25d7zd06v9ndqdccd2r0000gn/T/ipykernel_24973/1368001829.py:2: DtypeWarning: Columns (1,3,8,11,12,13,15,16,17,18,26) have mixed types. Specify dtype option on import or set low_memory=False.
  salmon_data = pd.read_csv("Alaskan-salmon1922-2017/data/ASL_master.csv")

## Salmon data
Preparing the salmon data to be entered into the relational database.

In [3]:
# assess whether the data types are what we expect
salmon_data.dtypes

Species                      object
Length.Measurement.Type      object
sampleYear                  float64
ASLProjectType               object
LocationID                   object
sampleDate                   object
Length                      float64
Weight                      float64
Sex                          object
Salt.Water.Age              float64
DataSource                   object
cardNo                       object
fishNum                      object
Age.Error                    object
Fresh.Water.Age             float64
Sex.Determination.Method     object
subSystem                    object
Flag                         object
Gear                         object
SASAP.Region                 object
LocationUnique               object
DistrictID                  float64
Sub.DistrictID              float64
Stat.area                   float64
Lat                         float64
Lon                         float64
AWC_CODE                     object
dtype: object

Yay! It looks like all of the data is in the right data type except for the sampleYear and sampleDate. But, there is no primary key. 
 
### Make a primary key for our salmon dataframe
A database requires a primary key that has no NA values and is unique to each row. Add an ID column to the salmon data to fullfil this requirement.

In [4]:
# add an id column to the salmon dataframe to be used as a primary key
salmon_data['salmon_id'] = salmon_data.index

In [5]:
# initial look at the dataframe
salmon_data.head()

,Species,Length.Measurement.Type,sampleYear,ASLProjectType,LocationID,sampleDate,Length,Weight,Sex,Salt.Water.Age,...,Gear,SASAP.Region,LocationUnique,DistrictID,Sub.DistrictID,Stat.area,Lat,Lon,AWC_CODE,salmon_id
0,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,...,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN,0
1,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,...,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN,1
2,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,...,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN,2
3,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,...,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN,3
4,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,4.0,...,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN,4

### Adjust data type

In [36]:
# convert salmon year to an int so we can give it type date in the database
salmon_data['sampleYear'] = salmon_data['sampleYear'].astype('Int64')

### Subset for the necessary data 

We don't need all of the columns for this analysis so we can subset.

In [6]:
# select the variables that are essential for the salmon dataframe 
salmon_data = salmon_data[['Species', 'Length.Measurement.Type', 'sampleYear', 'LocationID', 'sampleDate', 'Length', 'Weight', 'Sex','Salt.Water.Age', 'Fresh.Water.Age', 'Gear', 'Stat.area', 'DataSource']]

# Length dataset

In [ ]:
# view the length dataset
length_type.head()

,Length.Measurement.Type,Length_fill,LocationID,Species,ASLProjectType,sampleYear
0,mid-eye to fork of tail,NaN,108 Creek,coho,escapement,1998.0
1,mid-eye to fork of tail,NaN,108 Creek,coho,escapement,1999.0
2,mid-eye to fork of tail,NaN,108 Creek,coho,escapement,2000.0
3,mid-eye to fork of tail,NaN,18 Mile Slough,chum,escapement,2003.0
4,mid-eye to fork of tail,NaN,18 Mile Slough,chum,escapement,2004.0

In [9]:
# assess if the data types for the length need to be adjusted
length_type.dtypes

Length.Measurement.Type     object
Length_fill                 object
LocationID                  object
Species                     object
ASLProjectType              object
sampleYear                 float64
dtype: object

All of the data seems to be in adequate formats but above we just adjusted the year column to be a type integer. We should change the datatype of this year column to match. 

### Adjust datatype

In [ ]:
# check all of the unique values of the year column 
length_type['sampleYear'].unique()

array([1998., 1999., 2000., 2003., 2004., 1984., 1983., 1985., 1986.,
       1987., 1988., 1990., 1991., 1992., 1993., 2002., 2005., 2006.,
       2007., 2008., 1989., 1996., 2010., 2011., 2013., 2014., 1994.,
       1995., 1997., 2001., 2009., 2012., 2015., 1982., 1965., 1967.,
       1964., 1970., 1971., 1972., 1974., 1975., 1963., 1966., 1968.,
       1969., 1973.,   nan, 1976., 1960., 1978., 2016., 1979., 1980.,
       1981., 1977., 1961., 2017., 1962., 1959., 1958., 1957.])

In [11]:
# change year from float ot int
length_type['sampleYear'] = length_type['sampleYear'].astype('Int64')

# Location dataset

In [10]:
# assess if all of the data is in the right format
location.dtypes

SASAP.Region               object
SASAP.Region_Corrected     object
Location                   object
ASLProjectType             object
District                   object
Sub.District               object
LocationUnique             object
DistrictID                float64
Sub.DistrictID            float64
Stat.area                 float64
Lat                       float64
Lon                       float64
AWC_CODE                   object
source                     object
LocationID                 object
dtype: object

In [ ]:
# view the location data
location.head()

,SASAP.Region,SASAP.Region_Corrected,Location,ASLProjectType,District,Sub.District,LocationUnique,DistrictID,Sub.DistrictID,Stat.area,Lat,Lon,AWC_CODE,source,LocationID
0,Alaska Peninsula and Aleutian Islands,Alaska Peninsula and Aleutian Islands,NaN,commercial catch,302,19,Aleutians-commercial catch-302,302.0,NaN,NaN,NaN,NaN,NaN,NaN,Aleutians
1,Alaska Peninsula and Aleutian Islands,Alaska Peninsula and Aleutian Islands,Bear River,commercial catch,315,11,Bear River-commercial catch-31511,315.0,11.0,31511.0,NaN,NaN,NaN,NaN,Bear River
2,Alaska Peninsula and Aleutian Islands,Alaska Peninsula and Aleutian Islands,Bear River,escapement,315,11,Bear River-escapement-31511,315.0,11.0,31511.0,56.0389,-160.2734,315-11-10200,ADFG,Bear River
3,Alaska Peninsula and Aleutian Islands,Alaska Peninsula and Aleutian Islands,Bear River,test fishing,315,11,Bear River-test fishing-31511,315.0,11.0,31511.0,56.0389,-160.2734,315-11-10200,ADFG,Bear River
4,Alaska Peninsula and Aleutian Islands,Alaska Peninsula and Aleutian Islands,Bear River,test fishing,316,11,Bear River-test fishing-31511,315.0,11.0,31511.0,56.0389,-160.2734,315-11-10200,ADFG,Bear River

In [15]:
# subset for only necessary rows
location = location[['LocationUnique', 'SASAP.Region_Corrected','Location', 'ASLProjectType', 'District', 'Sub.District', 'Lat', 'Lon', 'LocationID']]

In [16]:
# change the name of the columns for easier interpretation
location_rename = location.rename(columns = {'SASAP.Region_Corrected' : 'LocationID'})

In [17]:
# adjust the location data
location = location.clean_names()

### Location data key

The primary key of the dataframe must be unique and non-null. Let's ensure it meets all of these qualifications.

In [18]:
# view duplicates based on the location unique
dup_location = location[location.duplicated(subset = ['locationunique'], keep = False)]
dup_location

,locationunique,sasap_region_corrected,location,aslprojecttype,district,sub_district,lat,lon,locationid
1,Bear River-commercial catch-31511,Alaska Peninsula and Aleutian Islands,Bear River,commercial catch,315,11,NaN,NaN,Bear River
2,Bear River-escapement-31511,Alaska Peninsula and Aleutian Islands,Bear River,escapement,315,11,56.038900,-160.273400,Bear River
3,Bear River-test fishing-31511,Alaska Peninsula and Aleutian Islands,Bear River,test fishing,315,11,56.038900,-160.273400,Bear River
4,Bear River-test fishing-31511,Alaska Peninsula and Aleutian Islands,Bear River,test fishing,316,11,56.038900,-160.273400,Bear River
5,Bear River-escapement-31511,Alaska Peninsula and Aleutian Islands,Bear River,escapement,315,12,56.038900,-160.273400,Bear River
...,...,...,...,...,...,...,...,...,...
2735,Rampart Rapids-subsistence catch-33452,Yukon,Rampart Rapids,subsistence catch,Yukon,Y5 (Subdistrict 5),65.337055,-151.082611,Rampart Rapids
2736,Rampart Rapids-commercial catch-33452,Yukon,Rapids Research Center,commercial catch,Yukon,Y5 (Subdistrict 5),NaN,NaN,Rampart Rapids
2737,Rampart Rapids-subsistence catch-33452,Yukon,Rapids Research Center,subsistence catch,Yukon,Y5 (Subdistrict 5),65.337055,-151.082611,Rampart Rapids
2763,Tanana River-escapement-33460,Yukon,Tanana River,escapement,Yukon,Y6 (Subdistrict 6),64.979281,-150.845454,Tanana River
2764,Tanana River-escapement-33460,Yukon,Tanana River Sonar,escapement,Yukon,Y6 (Subdistrict 6),64.979281,-150.845454,Tanana River

The location unique does in fact have duplicates as shown in the subset above. The column `locationunique` column appears to be created by joining the `location`, `aslprojecttype`, `district`, and `subdistrict` columns. These duplicates seem to just be errors in the creation of the key. We can remake the `locationunique` to avoid any issues when ingesting the data into the relational database.

Additionally, some of the rows needed to recreate the `locationunique` column are NA. To avoid losing any data we can fill the NA with the well known NA value of `999`. This will make unique `locationunique`.

In [19]:
# fill the na in sub_district with a filler 999
location['sub_district'] = location['sub_district'].fillna('999')
location['district'] = location['district'].fillna('999')
location['aslprojecttype'] = location['aslprojecttype'].fillna('999')
location['location'] = location['location'].fillna('999')

In [20]:
# remake the locationunique column because there are duplicates as it seems like the subdistrict wasn't included correctly
location['locationunique'] = location['location'] + location['aslprojecttype'] + location['district'] + location['sub_district']

In [23]:
print(f"There are now ",len(location[location['locationunique'].isnull()]), " are NAs in the locationunique column.")

There are now  0  are NAs in the locationunique column.

# Gear data

In [ ]:
# view the gaer data
gear.head()

                    Gear             SASAP.Gear
0                    NaN                    NaN
1  handpicked or carcass  handpicked or carcass
2            beach seine                  seine
3    sport hook and line    sport hook and line
4                   weir                   weir

In [14]:
# assess if the gear data is in the right data fromats
gear.dtypes

Gear          object
SASAP.Gear    object
dtype: object

In [ ]:

location.head()

,LocationUnique,SASAP.Region_Corrected,Location,ASLProjectType,District,Sub.District,Lat,Lon,LocationID
0,Aleutians-commercial catch-302,Alaska Peninsula and Aleutian Islands,NaN,commercial catch,302,19,NaN,NaN,Aleutians
1,Bear River-commercial catch-31511,Alaska Peninsula and Aleutian Islands,Bear River,commercial catch,315,11,NaN,NaN,Bear River
2,Bear River-escapement-31511,Alaska Peninsula and Aleutian Islands,Bear River,escapement,315,11,56.0389,-160.2734,Bear River
3,Bear River-test fishing-31511,Alaska Peninsula and Aleutian Islands,Bear River,test fishing,315,11,56.0389,-160.2734,Bear River
4,Bear River-test fishing-31511,Alaska Peninsula and Aleutian Islands,Bear River,test fishing,316,11,56.0389,-160.2734,Bear River

In [77]:
# join the salmon data with the location data to get the unique location column
salmon_data = pd.merge(salmon_data, location, how = "inner", on = 'LocationID')

KeyError: 'LocationID'

In [52]:
salmon_data.head()

,Species,Length.Measurement.Type,sampleYear,LocationID,sampleDate,Length,Weight,Sex,Salt.Water.Age,Fresh.Water.Age,...,Stat.area,DataSource,LocationUnique,SASAP.Region_Corrected,Location,ASLProjectType,District,Sub.District,Lat,Lon
0,chinook,length not taken,1992,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,...,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-test fish...,Southeast,District 105 Test Seine,test fishing,105,10,NaN,NaN
1,chinook,length not taken,1992,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,...,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-test fish...,Southeast,District 105 Test Troll,test fishing,105,10,NaN,NaN
2,chinook,length not taken,1992,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,...,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-commercia...,Southeast,District 105 Traditional Seine,commercial catch,105,10,NaN,NaN
3,chinook,length not taken,1992,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,...,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-commercia...,Southeast,District 105 Traditional Troll,commercial catch,105,10,NaN,NaN
4,chinook,length not taken,1992,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,...,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-test fish...,Southeast,District 105 Troll Sublegal,test fishing,105,10,NaN,NaN

In [53]:
# reselect the columns we need
salmon_data = salmon_data[['Species', 'Length.Measurement.Type', 'sampleYear', 'sampleDate', 'Length', 'Weight', 'Sex','Salt.Water.Age', 'Fresh.Water.Age', 'Gear', 'Stat.area', 'DataSource', 'LocationUnique']]

# clean column names
salmon_data = salmon_data.clean_names()

In [54]:
salmon_data.head()

,species,length_measurement_type,sampleyear,sampledate,length,weight,sex,salt_water_age,fresh_water_age,gear,stat_area,datasource,locationunique
0,chinook,length not taken,1992,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,troll,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-test fish...
1,chinook,length not taken,1992,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,troll,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-test fish...
2,chinook,length not taken,1992,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,troll,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-commercia...
3,chinook,length not taken,1992,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,troll,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-commercia...
4,chinook,length not taken,1992,1992-03-31,NaN,NaN,examined but did not identify,3.0,1.0,troll,10510.0,ADFG Southeast and Westward,Affleck Canal/Spanish Is/Louise Cove-test fish...

In [55]:
# look at the unique values
print(salmon_data['species'].unique())
print(salmon_data['length_measurement_type'].unique())
print(salmon_data['sampleyear'].unique())
print(salmon_data['sampledate'].unique())
print(salmon_data['length'].unique())
print(salmon_data['weight'].unique())
print(salmon_data['sex'].unique())
print(salmon_data['salt_water_age'].unique())
print(salmon_data['fresh_water_age'].unique())
print(salmon_data['gear'].unique())
print(salmon_data['stat_area'].unique())
print(salmon_data['locationunique'].unique())

['chinook' 'chum' 'coho' 'pink' 'sockeye']
['length not taken' 'mid-eye to fork of tail' 'mid-eye to hypural plate'
 'post orbit to hypural plate' 'post-orbit to fork of tail'
 'tip of snout to fork of tail' 'tip of snout to tip of tail' 'unknown'
 nan 'cleithral arch to fork']
<IntegerArray>
[1992, 2002, 1997, 1999, 2000, 2001, 2003, 1996, 1991, 1995, 2007, 1998, 1969,
 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, <NA>, 1979, 1980, 1981,
 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1993, 1994, 2004, 2005,
 2006, 2008, 2009, 2010, 2011, 2012, 1966, 1968, 2013, 2014, 2015, 2016, 1964,
 1965, 1967, 2017, 1961, 1959, 1962, 1963, 1957, 1960, 2018, 1937, 1958]
Length: 64, dtype: Int64
['1992-03-31' '2002-07-15' '2002-08-30' ... '1977-05-26' '1977-06-02'
 '1978-05-20']
[  nan  781.  768. ...  114.  113. 5440.]
[  nan  498.  320. ... 2080.  654. 2780.]
['examined but did not identify' 'male' 'female' 'unknown' nan '2' '1' 1.0
 2.0 0.0 3.0 '3']
[ 3.  4. nan  2.  1.  5.  6.  0.  7.  8.]
[ 1.  0. nan  2.  6.  3.  4.  5.  8.]
['troll' 'gillnet' 'seine' 'hatchery' nan 'fishwheel'
 'sport hook and line' 'unknown' 'dip net' 'handpicked or carcass' 'weir'
 'trap' 'gillnet and fishwheel' 'electrofishing' 'gig' 'pots' 'spear'
 'screw' 'fyke net']
[10510. 10141. 18230. 11218. 10420. 10210. 10350. 10146. 11510. 10961.
 10240. 11338. 10145.    nan 11031. 10430. 10435. 10129. 10380. 10325.
 10260. 10951. 10311. 10440. 10250. 11391. 11381. 10111. 11016. 10410.
 10280. 11335. 18270. 10910. 10941. 10121. 10641. 11132. 10321. 10550.
 11216. 10450. 11322. 18310. 18220. 11222. 24741. 24117. 24530. 24461.
 24441. 24730. 22340. 18240. 33412. 10720. 11217. 10735. 33444. 33447.
 11150. 25615. 25620. 11011. 31511. 10122. 33510. 11312. 33414. 10360.
 10740. 11511. 10130. 11015. 11611. 11114. 11245. 10810. 27274. 27240.
 27262. 27260. 27230. 27220. 27110. 11532. 11533. 10850. 33470. 11013.
 10643. 18221. 10153. 10151. 11351. 25810. 25840. 25830. 25870. 25860.
 25880. 25855. 10930. 11480. 33462. 18930. 11021. 11014. 11365. 11213.
 11250. 11263. 33442. 11473. 11470. 33320. 33446. 10942. 11214. 33453.
 11265. 10140. 11394. 11425. 11355. 11440. 28490. 31620. 11362. 33512.
 10642. 10330. 25510. 11221. 11371. 33110. 11421. 11397. 11395. 11613.
 11614. 11321. 11311. 11363. 26255. 26235. 26260. 26275. 26245. 26240.
 26280. 18320. 33461. 33424. 25450. 25120. 25335. 25625. 25720. 25311.
 25760. 25110. 25851. 25410. 25938. 25939. 10230. 33421. 10841. 11343.
 11334. 10195. 31330. 31310. 10127. 10142. 11531. 32530. 32535. 32531.
 32540. 32533. 32541. 32532. 32510. 32511. 18260. 10845. 33425. 11211.
 11345. 11361. 11241. 10123. 10220. 11331. 10125. 33423. 11423. 11131.
 11427. 11450. 10911. 10943. 31710. 11034. 10963. 10541. 11134. 10113.
 10860. 11022. 33540. 33452. 10610. 10920. 10531. 10620. 11354. 10952.
 33443. 10944. 10390. 10945. 33350. 10543. 11341. 11359. 18280. 11373.
 11111. 28211. 28220. 28265. 28225. 28240. 28245. 28242. 28230. 28235.
 28210. 28275. 28255. 28270. 11024. 10950. 33422. 11396. 11140. 33454.
 11393. 25610. 25630. 25520. 25710. 25740. 25770. 11392. 10126. 10962.
 11012. 10143. 10340. 32672. 32670. 32671. 32610. 32620. 32630. 32611.
 10270. 10147. 11121. 11017. 33360. 10710. 10630. 11475. 11212. 11434.
 33550. 10128. 10190. 10185. 11332. 18110. 25430. 25420. 25331. 25440.
 25431. 25313. 25150. 25421. 11219. 11032. 10830. 10840. 10644. 33410.
 33420. 33430. 33440. 33450. 33460. 10730. 33520. 10171. 32420. 10155.
 33463. 11534. 21220. 11135. 10115. 33464. 33340. 11117. 33330. 33310.
 33530. 33514. 10177. 10180. 33431. 33513. 33455. 33511. 33432. 33415.
 33417. 10370. 11431. 11612. 33445. 11372. 11342. 11340. 11120. 11366.
 11143. 11133. 11115. 10880. 25232. 23206. 24116. 23209. 24983. 24980.
 24950. 24940. 23223. 24985. 24945. 23130. 23105. 23205. 24109. 23207.
 24970. 24975. 24130. 23201. 23204. 22160. 22521. 22220. 11155. 33120.
 31160. 28442. 28324. 26215. 28520. 28321. 11280. 28467. 10124. 25820.
 32210. 22530. 22520. 11472. 10940. 31420. 31412. 11033. 31625. 31220.
 31240. 31210. 11344. 20030. 25230. 10365. 28480. 10110. 32426. 28323.
 10520. 22660. 33112. 31152. 11242. 25333. 25312. 32110. 31132. 28436.
 28445. 22720. 33210. 11520. 22130. 10144. 20020. 22230. 22830. 22330.
 22150. 22210. 22140. 22120. 11190. 11433. 11112. 11248. 11244. 28437.
 28540. 28317. 28462. 21215. 28455. 31610. 31720. 28326. 28475. 22440.
 22860. 22840. 22430. 22310. 22110. 22410. 22420. 10542. 24750. 25234.
 25921. 25170. 31820. 21211. 25182. 18330. 18325. 25741. 18390. 26220.
 19241. 25941. 11215. 18355. 18380. 19242. 18510. 18505. 25730. 10913.
 10315. 21230. 28434. 10635. 31231. 25183. 30231. 28320. 25140. 10173.
 11336. 26265. 25160. 25231. 28125. 22347. 22348. 22168. 22235. 22247.
 22222. 22221. 22227. 22820. 22667. 22630. 22651. 22662. 22640. 22661.
 22620. 32520. 18222. 10820. 10323. 25743. 24432. 24114. 24620. 24955.
 24431. 24110. 24330. 24120. 25240. 25250. 26250. 31520. 26295. 26290.
 22510. 25750. 27292. 32220. 32230. 25141. 11023. 10120. 31622. 10215.
 32413. 32411. 32421. 32422. 32423. 32534. 25943. 25185. 27560. 11313.
 11353. 25130. 32631. 32180. 25184. 27374. 25731. 27143. 22320. 21210.
 10745. 33556. 11267. 31629. 31611. 26230. 10624. 30225. 30235. 31707.
 28131. 28150. 28130. 25942. 25911. 22161. 28412. 25925. 25742. 25540.
 28180. 28170. 28165. 28162. 28115. 25852. 25640. 25314. 25334. 28438.]
['Affleck Canal/Spanish Is/Louise Cove-test fishing-10510'
 'Affleck Canal/Spanish Is/Louise Cove-commercial catch-10510'
 'Alava To Sykes-test fishing-10141' ... 'Blue Bill Lake-escapement-312'
 'Three Hills-escapement-31610' 'Upper Thumb-escapement-unknown']

In [56]:
# change weird unknowns to NAs
salmon_data.loc[salmon_data['length_measurement_type']== 'unknown', 'length_measurement_type'] = np.nan
print(salmon_data['length_measurement_type'].unique())

['length not taken' 'mid-eye to fork of tail' 'mid-eye to hypural plate'
 'post orbit to hypural plate' 'post-orbit to fork of tail'
 'tip of snout to fork of tail' 'tip of snout to tip of tail' nan
 'cleithral arch to fork']

In [57]:
# change weird unknowns to NA
# filter rows that are not 'male' and not 'female'
invalid_mask = (~salmon_data['sex'].isin(['male', 'female']))

# fill these rows with NA
salmon_data.loc[invalid_mask, 'sex'] = np.nan

print(salmon_data['sex'].unique())

[nan 'male' 'female']

In [ ]:
# save data to a csv file
# salmon_data.to_csv('salmon_data_clean.csv')

## Clean location dataframe

In [62]:
print(location['locationunique'].unique())
print(location['sasap_region_corrected'].unique())
print(location['location'].unique())
print(location['aslprojecttype'].unique())
print(location['district'].unique())
print(location['sub_district'].unique())
print(location['lat'].unique())
print(location['lon'].unique())
print(location['locationid'].unique())

['Aleutians-commercial catch-302' 'Bear River-commercial catch-31511'
 'Bear River-escapement-31511' ...
 'Yukon Crossing, Y.T., Canada (Village/City)-escapement-NA'
 'Yukon District-subsistence catch-NA' nan]
['Alaska Peninsula and Aleutian Islands' 'Bristol Bay' 'Chignik'
 'Cook Inlet' 'Copper River' 'Kodiak' 'Kotzebue' 'Kuskokwim'
 'Norton Sound' 'Prince William Sound' 'Southeast' 'Yukon' nan]
[nan 'Bear River' 'Bear River (genetics)' ... 'Y6 (Subdistrict 6)'
 'Yukon Crossing, Y.T., Canada (Village/City)' 'Yukon District']
['commercial catch' 'escapement' 'test fishing' nan 'sport catch'
 'hatchery cost recovery' 'mark/recapture' 'personal use' 'brood stock'
 'subsistence catch' 'test fish' 'unknown' 'commercial common property'
 'mixed ccp and hcr' 'sport fish' 'brood excess']
['302' '315' '316' '311' '312' '284' '283' '324' '313' '282' '285' nan
 '318' '314' '31' '317' '303' '281' '322' '325' '326' '321' '271' '272'
 '275' '273' '270' '259' '231' '241' '244' '249' '247' '240' '245' '232'
 '246' '212' '200' '211' '213' '202' '216' '252' '251' '257' '262' '256'
 '258' '254' '253' '255' '225' '265' 'Kotzebue' 'Kuskokwim'
 'Port Clarence' 'Norton Sound' '226' '222' '221' '228' '227' '224' '223'
 '230' '233' '220' '229' '106' '115' '111' '105' '182' '101' '109' '107'
 '102' '108' '112' '104' '110' '113' '103' '116' '171' '172' '173' '174'
 '114' '152' '154' '156' '157' '183' '186' '191' '192' '189' '181' '185'
 'Yukon' 'Northern' 'Canada']
['19' '11' '12' '20' nan '30' '60' '37' '42' '45' '64' '10' '24' '40' '17'
 '21' '34' '62' '67' '55' '22' '90' '25' '29' '35' '7' '75' '13' '80' '0'
 '3' '50' '31' '23' '26' '61' '15' '33' '65' '70' '47' '52' '32' '36' '38'
 '206' '16' '91' '41' '71' '72' '20/30' '5' '00' '74' '1' '43' '110' '92'
 '05' '09' '83' '14' '01' '85' '06' '07' '04' '620' '95' '82' '39' '51'
 '27' '84' 'X2 (Noatak Special Harvest Area)' 'X1 (Kotzebue Sound)'
 'W1 (Subdistrict 1)' 'W2 (Subdistrict 2)' 'W3 (Subdistrict 3)'
 'W5 (Goodnews Bay Subdistrict)' 'W4 (Subdistrict 4)'
 'Port Clarence Subdistrict' 'Z2 (Golovin Bay Subdistrict)'
 'Z6 (Unalakleet Subdistrict)' 'Z1 (Nome Subdistrict)'
 'Z4 (Norton Bay Subdistrict)' 'Z3 (Moses Point Subdistrict)'
 'Z5 (Shaktoolik Subdistrict)' '48' '68' '18' '81' '46' '44' '9' '89' '4'
 '28' '49' '66' '2' '53' '63' '73' '94' '97' '54' '59' '96' '93'
 'Y1 (Subdistrict 1)' 'Y2 (Subdistrict 2)' 'Y4 (Subdistrict 4)'
 'Y6 (Subdistrict 6)' 'Y5 (Subdistrict 5)' 'Y7 (Yukon - Canada)'
 'Y3 (Subdistrict 3)']
[        nan 56.0389     58.6464951  55.25496254 55.15871922 55.68695365
 56.61277298 53.98525038 56.80597951 55.09728748 55.14353052 55.810523
 55.731      55.292863   56.2163     53.8963     55.0109     56.43917637
 59.06201854 58.0390351  58.24612254 59.04589629 58.71314978 59.32838685
 58.7969     58.71732466 58.62403922 58.9061423  58.8676571  58.8692797
 59.52652212 57.55815409 57.48809726 59.27149382 56.392      56.2615981
 56.22999512 59.90721045 60.21253513 60.18765143 62.73811342 62.47307788
 59.21669612 59.20459394 59.55074495 60.248435   59.5510947  59.59664696
 59.64252926 59.34825845 61.44856291 60.19191707 62.0050096  61.57055038
 60.30599934 60.50965248 56.17156635 59.11997203 59.11050985 60.439145
 59.30938168 60.477819   60.4519     61.9655661  62.70563105 62.17592335
 61.47739506 61.52723941 61.63226236 60.38208062 60.56150375 60.29418368
 60.36114663 60.39666038 60.46358948 61.02621763 62.61403904 60.26692163
 60.55195784 60.58705705 60.38141907 60.39705167 61.3853828  60.36782573
 60.26756333 60.46058527 60.45351079 60.35534364 60.40032654 60.27442399
 60.37616972 60.40557795 58.0815     57.1641     57.19782763 57.75811702
 57.1289     57.2027     57.12198678 58.24848285 57.563      58.19060571
 58.1963     57.7784     58.173      57.45842706 58.37761699 58.27233566
 57.5263     57.15034208 57.59537777 58.606005   58.2765     57.6696
 57.05645018 57.35619822 66.858501   66.18194    66.07642    67.91666667
 66.07444    67.91889    66.971864   66.96098671 66.921158   66.898559
 66.681261   68.05906213 67.208214   67.673035   66.836144   67.16465566
 66.848545   66.993611   67.00745579 67.13403523 68.38333333 60.909444
 61.691175   61.50958295 61.57583    60.789668   61.574381   62.95972
 61.693454   60.214921   60.20389    60.616808   61.91878684 61.906198
 59.10694    59.15992    60.856944   60.653611   61.538488   61.532352
 59.76761667 60.429556   61.05083    60.85806    60.84810009 60.8121
 60.32648088 59.86077    62.95616    61.461944   60.696667   60.706839
 63.012457   60.9873     60.721389   59.75415    61.06278    62.79122209
 62.891493   61.77       63.05100267 61.91917    61.0675     61.101888
 60.98690407 60.342177   65.42575421 65.02762842 64.96786431 63.92222222
 64.5735     64.75895777 64.86639    64.82021838 64.602561   64.71955373
 64.69833    64.696512   64.8094257  64.496833   63.8876524  63.26706842
 65.12150107 64.91139    64.37005695 64.59028    64.5043644  64.58317973
 64.73945    63.89103999 63.86284613 64.55861    60.93458621 60.75421557
 60.96717637 60.90444181 60.51359508 60.97615643 60.22284264 60.47675507
 61.07256464 61.09500733 61.07671832 60.36403265 60.74698533 60.45973014
 60.62558955 60.31865399 60.45971518 60.94167622 60.93255969 60.44914157
 60.452558   60.84073516 60.96519971 61.01931904 60.991158   60.502
 60.95428594 60.36193388 61.01166469 60.86779586 60.45473074 60.70610429
 60.85778271 61.02358677 60.86023698 60.95349797 61.08225007 61.00219589
 60.36493869 60.75954392 60.65126018 60.70072568 60.29687945 61.08651729
 61.0844143  60.24941369 60.71466703 60.67562226 60.9576802  60.99666741
 60.64393854 60.7787272  61.05165491 60.88937498 60.18786974 60.84794169
 60.75582979 61.06868693 61.00595609 61.03658539 60.798516   61.01429316
 60.81897886 60.23613543 60.24314216 56.12618349 59.36932332 58.17570195
 59.42801018 59.29293491 56.50434398 59.16582275 55.57591498 56.63997
 59.45033043 58.80730854 59.56690546 58.38052206 55.2974368  55.8535396
 59.40470079 55.38193683 58.84640014 55.72591689 57.70696859 55.40200803
 55.10519366 55.9825981  55.64054412 57.30609932 55.81747724 59.37213527
 59.32015028 55.83273279 56.83       57.24053    55.75864687 57.6916
 57.25887042 59.32577106 59.22620966 58.03314627 58.16786283 55.53947185
 56.61334908 56.51899612 55.1311821  55.13537247 58.64693    59.10378571
 55.15598013 54.77414998 58.51427506 56.82790468 57.15969894 54.95252943
 58.33050184 55.93555454 58.54314819 58.07832258 58.09505976 56.47566624
 58.15835599 56.97025561 56.70238835 58.25907    56.20498484 55.46354659
 57.5922345  55.94061023 55.75256553 55.65066885 59.41783986 55.99652462
 55.32658431 55.17164093 55.02947239 58.22610726 58.07075087 58.894798
 55.09855422 55.0321619  58.09384393 55.84875584 55.81048774 57.04486347
 57.067489   59.31298578 54.97423358 57.70235484 56.53032685 57.49361883
 55.5594952  57.17040282 55.0218718  55.33601594 55.34135067 55.84035252
 58.727557   58.04200257 57.63999679 55.01444344 55.54888984 59.40275048
 60.11632    57.66815071 58.5054     56.28407412 56.4721855  59.233695
 56.62009032 58.8449554  57.64754701 58.39070469 57.40284    57.58191834
 55.51044039 55.90559569 58.03722049 59.38566137 58.12455    58.491522
 59.45381678 55.92754322 55.98559879 55.42625128 58.42411664 55.69511371
 55.95676853 55.96436127 55.56957568 56.63891757 56.45990585 55.12753241
 58.38115944 59.47191826 59.63998611 59.49301724 55.59254703 58.775013
 59.066176   57.25553037 58.956845   56.09852214 58.05567303 58.40926158
 56.68492843 59.23408295 55.4276231  59.51389363 57.84191857 56.83975397
 57.6306334  56.74333    56.62991276 56.64365352 55.45025457 56.47633635
 58.04737466 55.99485883 55.88841186 56.26266432 56.866573   56.007881
 56.28065378 58.330475   56.97683493 55.90228825 57.77043816 56.9759727
 55.95111991 56.37948939 58.71535032 57.04931807 57.289319   56.80580362
 56.71329995 58.25739143 56.09081883 57.62556779 57.51937021 59.44608704
 59.45795207 59.49383    55.87520991 58.08850499 58.13484877 55.81965685
 58.41648541 56.69171749 56.15019396 57.99440381 57.94379212 55.9882847
 58.12213    59.84363    59.46743574 56.18209016 55.27571124 55.39863098
 55.73290542 55.35219411 59.03352    59.39054604 60.07775116 56.375883
 58.339861   55.82516465 55.37643885 56.69927    55.75270581 55.40862137
 59.40590902 57.93699855 55.4741339  58.51527348 55.91811491 58.50153787
 62.684228   62.03259687 62.14938086 62.655659   62.656746   62.96721377
 62.68139    64.3525     62.163888   66.361745   62.75322    61.881944
 64.824266   62.177777   64.14293    66.63502531 65.139313   64.82395384
 60.18149768 65.504436   66.21803    61.585      64.060075   64.09532185
 64.15418074 61.911564   64.786121   64.772477   62.777664   64.844851
 62.52079    66.5        62.632507   66.563477   64.73938    65.23725347
 64.31844499 63.292065   65.875826   66.55776747 65.67222    62.199948
 61.49387    65.697302   62.680194   62.19638    66.79055    64.48139
 63.9833     64.3185     65.38629649 61.875      62.038888   63.034167
 64.880278   66.6245759  63.905886   62.05       65.005005   61.8125
 63.55       64.77820533 60.670833   62.899132   65.15224    62.593
 60.095833   62.087      64.561157   60.25       62.1        64.724477
 64.72806938 61.569151   63.92564514 61.964006   61.951371   62.035485
 66.57667    65.50783333 65.337055   64.26392018 61.983333   64.73877
 61.787247   64.48254432 64.530208   66.73944    62.049621   66.005177
 60.8125     60.841666   65.172119   64.976667   64.97928121 62.283333
 60.173965   60.566666   64.35323154 65.51586569 60.69555556 60.279166
 62.354     ]
[         nan -160.2734    -156.5873979 -162.8092373 -162.8058244
 -161.0414646 -159.568744  -166.7318887 -158.6632898 -163.2300704
 -162.6291139 -161.2564572 -160.0934    -162.762089  -160.055
 -166.4596    -162.6734    -160.0143251 -156.4869164 -156.8564297
 -157.6254391 -159.2663971 -158.8739252 -155.89715   -157.0993
 -157.0529839 -156.5209958 -157.7335835 -158.6049481 -158.7624993
 -159.7199888 -156.7963411 -157.5958357 -158.5822057 -158.937
 -158.7122418 -158.8110303 -149.7385203 -150.8062938 -149.3873373
 -150.1172741 -151.4544955 -154.1439766 -154.2085101 -151.2406061
 -152.5830789 -150.2793329 -150.2526724 -150.2329808 -151.9182106
 -149.8280546 -149.3760057 -151.3924855 -151.557459  -151.2447648
 -151.1069727 -134.1308042 -154.2615684 -154.2541517 -151.9004419
 -151.3165321 -149.72298   -149.9869    -151.5622103 -148.8797443
 -150.1277698 -150.5345284 -148.9022134 -150.562317  -145.4410379
 -144.7775997 -144.3011442 -144.0075369 -144.0349716 -144.8891737
 -144.3166714 -143.775637  -144.1904541 -145.6750342 -145.6493152
 -144.1108769 -144.6112096 -143.2829031 -144.5411365 -144.7038036
 -145.1861603 -144.6594578 -144.4541943 -144.6544674 -144.2631608
 -144.0924789 -144.2947588 -152.8286    -154.2287    -154.538493
 -152.4783685 -154.0287    -154.0573    -153.9151235 -154.2654445
 -154.3843    -152.3724245 -152.3681    -153.6666    -153.2158
 -152.4513767 -152.3304712 -152.4313286 -152.7619    -154.3800753
 -153.5559173 -153.7788054 -152.8367    -153.3737    -154.3610157
 -153.9981496 -156.31055   -161.07889   -162.722797  -164.666667
 -162.7025    -162.34694   -160.430946  -160.4035869 -160.54184
 -162.590618  -163.086548  -161.7893985 -162.482278  -162.851715
 -161.042962  -159.4632628 -155.685024  -162.827854  -162.5135691
 -161.0213783 -163.8       -161.431389  -157.754745  -159.3819497
 -159.48722   -161.759262  -159.818802  -154.89667   -157.761955
 -162.021217  -162.24861   -162.172108  -157.6939358 -157.72162
 -161.476536  -160.6119    -161.581389  -162.108889  -160.316963
 -160.21019   -161.0602667 -162.448528  -159.17028   -161.23694
 -157.8525375 -161.4318    -160.8527976 -161.130157  -155.589237
 -158.639167  -161.951944  -161.76238   -154.381943  -159.9984
 -161.768333  -161.905222  -159.1944    -154.4953554 -154.577036
 -156.59111   -155.7459416 -156.24306   -154.40861   -160.963354
 -160.5501778 -162.665935  -165.7846786 -163.029759  -164.076227
 -160.661111  -164.9373    -163.4608668 -165.69972   -160.6244426
 -163.1113203 -162.0180961 -162.03472   -162.033749  -163.4461663
 -165.218833  -160.657705  -162.6037943 -164.7587819 -164.97917
 -160.9715195 -166.2475    -165.4234565 -164.4129429 -161.88806
 -160.478409  -160.7153481 -160.92083   -147.7563152 -145.9747245
 -147.2816841 -147.7110283 -146.1167077 -147.3746901 -147.270187
 -148.1888179 -147.9109022 -147.817315  -147.8804296 -146.6037807
 -146.2252472 -146.5367443 -148.2073076 -146.582703  -146.4504456
 -146.5657822 -147.3272727 -148.1181799 -148.104635  -146.3832719
 -148.0002821 -146.6050494 -148.1984554 -145.863     -146.6304424
 -148.2411524 -147.676986  -146.1771767 -146.4764703 -145.8996479
 -146.5204508 -146.6461974 -148.3858739 -148.329945  -147.4415174
 -146.4905849 -146.4963564 -146.1753627 -148.4554822 -148.3978563
 -147.0086854 -146.1357051 -146.4324585 -147.1984523 -145.899857
 -148.294464  -147.6880886 -147.2828768 -145.8087146 -146.2720371
 -146.8060097 -146.2351275 -147.3208534 -148.4106084 -148.4772879
 -146.7929338 -147.2705227 -146.5572115 -148.088703  -147.4142835
 -146.1857161 -147.2249112 -147.2082925 -133.1428949 -135.8337165
 -134.5609103 -139.5386846 -139.0930713 -134.0431637 -138.557567
 -132.7070825 -132.2       -139.2038616 -134.9604296 -135.9919134
 -134.6419269 -130.6489753 -130.6318944 -135.6761601 -131.4725448
 -134.9700146 -132.1684038 -136.115897  -130.6074118 -130.6274387
 -130.7579243 -131.3652275 -134.4440073 -130.9332636 -135.9432546
 -135.5454974 -130.8555603 -131.7658    -131.8697    -133.4721135
 -132.3014    -135.0096435 -135.8943612 -135.5098265 -133.8096258
 -133.3291194 -133.3218005 -132.8265193 -134.670875  -132.333369
 -132.0520614 -131.8118    -138.50863   -132.6694041 -132.9009537
 -135.5226604 -134.6938337 -133.1487523 -130.4716022 -134.5990912
 -130.042258  -133.6829487 -135.4820753 -135.4214914 -132.1589704
 -133.626145  -133.9351918 -134.7524926 -131.8068    -131.6206058
 -132.6988403 -134.3308868 -132.9734741 -131.8070003 -131.9710888
 -136.051002  -131.2990399 -131.5254825 -132.5796385 -130.3168185
 -134.5010163 -136.545172  -133.130609  -130.6461353 -130.6858007
 -135.5792629 -130.8729344 -131.0630159 -135.3114936 -130.361929
 -139.1536417 -132.1097051 -135.2204374 -133.1422908 -134.3967206
 -132.5781856 -135.274858  -132.1717394 -130.4757393 -131.6414116
 -130.8521086 -132.874927  -134.3414478 -136.0813626 -132.3926512
 -133.0975427 -135.9341418 -137.033     -134.9389182 -132.5419
 -132.3960564 -133.6642592 -133.261522  -134.1182891 -134.9494356
 -136.0441843 -134.6330921 -135.103261  -135.9152674 -131.5169592
 -130.7876359 -133.9394769 -135.9916474 -131.3792    -132.613472
 -139.6238607 -132.7667235 -130.6314232 -131.5101817 -133.9709095
 -131.6264686 -130.0643158 -131.8402999 -132.7089648 -133.2502287
 -132.2060381 -132.1845981 -134.5983329 -136.0343254 -139.3653116
 -136.0629562 -131.5926209 -132.079705  -133.024187  -135.3462999
 -133.203618  -133.1379314 -135.7882468 -135.4325363 -132.306356
 -135.4854591 -132.4678609 -139.7616453 -135.0346522 -133.0564383
 -133.9964567 -134.9433    -133.9984765 -134.0540532 -132.9908293
 -132.1465867 -133.806306  -130.6182738 -132.6186676 -133.3305504
 -135.299633  -131.573683  -133.1681454 -134.473622  -135.1474711
 -130.0279432 -135.4443099 -135.3133401 -133.2413334 -134.6522334
 -134.9435693 -135.227909  -131.828577  -134.2764144 -132.1067587
 -134.3238099 -133.5047132 -135.9780385 -134.9598629 -139.5677997
 -139.5714325 -139.1667    -130.7411731 -135.2882673 -133.72166
 -133.1551856 -134.549366  -132.2186287 -133.4450628 -134.3484787
 -133.6916013 -132.9027361 -131.3207    -136.6541    -139.6153466
 -132.1491149 -133.0797221 -130.0626852 -131.5190877 -132.888692
 -132.2209    -135.8686253 -143.0911588 -134.85521   -130.663633
 -130.9280627 -131.8297773 -130.9928    -130.7023386 -131.7135467
 -135.9263143 -135.8198066 -131.5363569 -134.7450954 -131.7966493
 -133.7855802 -164.659481  -163.2433505 -162.8008518 -160.209237
 -160.192509  -160.7075391 -160.20083   -150.215     -135.083333
 -147.402534  -164.498634  -134.916666  -157.379665  -133.216666
 -145.633303  -146.0165754 -147.419701  -147.2763211 -154.5661118
 -150.140018  -155.49188   -166.1883333 -139.430923  -145.5531673
 -145.8598467 -161.029701  -141.201439  -141.043735  -164.543953
 -147.720795  -163.850098  -138.416666  -164.761963  -145.267264
 -156.927962  -157.750924  -145.1290191 -159.696836  -149.721422
 -152.2163703 -149.80778   -159.770393  -165.903168  -156.394501
 -137.140111  -159.7175    -151.20028   -149.13472   -158.9333
 -158.7038    -158.5499521 -139.716666  -140.441666  -163.553333
 -157.700833  -151.5778915 -148.998835  -135.658333  -150.627208
 -162.020865  -137.433333  -155.51365   -134.466666  -164.10347
 -149.3398    -136.882     -132.495833  -163.608     -149.091095
 -132.566666  -136.301388  -158.107681  -158.1923732 -161.861572
 -150.8350405 -160.239973  -162.855919  -163.260857  -145.31389
 -150.1428333 -151.082611  -158.7327192 -132.433333  -155.482813
 -161.321526  -146.6785421 -149.133109  -144.56445   -163.181906
 -149.104042  -133.858333  -135.183333  -152.085487  -150.8425
 -150.8454536 -136.323611  -132.74231   -134.9       -150.219382
 -152.2111964 -135.0397222 -132.55      -136.501    ]
['Aleutians' 'Bear River' 'Bechevin Bay' ...
 'Yukon Crossing, Y.T., Canada (Village/City)' 'Yukon District' nan]

In [73]:
# view duplicates based on the location unique
dup2_location = location[location.duplicated(subset = ['locationunique'], keep = False)]
dup2_location

,locationunique,sasap_region_corrected,location,aslprojecttype,district,sub_district,lat,lon,locationid
337,Chignik Lagooncommercial catch27110,Chignik,Chignik Lagoon,commercial catch,271,10,NaN,NaN,Chignik Lagoon
338,Chignik Lagooncommercial catch27110,Chignik,Chignik Lagoon,commercial catch,271,10,NaN,NaN,Chignik Lagoon
479,Bering Rivercommercial catch2000,Copper River,Bering River,commercial catch,200,0,NaN,NaN,Bering River
480,Bering Rivercommercial catch2000,Copper River,Bering River,commercial catch,200,0,NaN,NaN,Bering River
485,Copper Rivercommercial catch2120,Copper River,Copper River,commercial catch,212,0,NaN,NaN,Copper River
488,Copper Rivercommercial catch2120,Copper River,Copper River,commercial catch,212,0,NaN,NaN,Copper River
1340,Prince William Sound Generalcommercial catch2200,Prince William Sound,Prince William Sound General,commercial catch,220,0,NaN,NaN,Prince William Sound
1342,Prince William Sound Generalcommercial catch2200,Prince William Sound,Prince William Sound General,commercial catch,220,0,NaN,NaN,Prince William Sound General

In [74]:
# drop duplicates in unique location 
location = location.drop_duplicates(subset = 'locationunique', keep = 'first')

In [ ]:
# save data to a csv file
# location.to_csv('location_clean.csv')

## Clean length_type

In [ ]:
length_type = length_type.clean_names()

In [ ]:
length_type

,length_measurement_type,length_fill,locationid,species,aslprojecttype,sampleyear
0,mid-eye to fork of tail,NaN,108 Creek,coho,escapement,1998
1,mid-eye to fork of tail,NaN,108 Creek,coho,escapement,1999
2,mid-eye to fork of tail,NaN,108 Creek,coho,escapement,2000
3,mid-eye to fork of tail,NaN,18 Mile Slough,chum,escapement,2003
4,mid-eye to fork of tail,NaN,18 Mile Slough,chum,escapement,2004
...,...,...,...,...,...,...
16522,mid-eye to fork of tail,NaN,Zimovia Straight,chinook,commercial catch,1991
16523,mid-eye to fork of tail,NaN,Zimovia Straight,chinook,commercial catch,2004
16524,mid-eye to fork of tail,NaN,Zimovia Straight,chinook,commercial catch,2005
16525,mid-eye to fork of tail,NaN,Zimovia Straight,chinook,commercial catch,2007
16526,mid-eye to fork of tail,NaN,Zimovia Straight,chinook,commercial catch,2008

In [ ]:
print(length_type['length_measurement_type'].unique())
print(length_type['length_fill'].unique())
print(length_type['locationid'].unique)

['mid-eye to fork of tail' 'length not taken' nan
 'post orbit to fork of tail' 'tip of snout to fork of tail'
 'post orbit to hypural plate' 'mid-eye to hypural plate'
 'tip of snout to tip of tail' 'post-orbit to fork of tail'
 'cleithral arch to fork']
[nan 'unknown' 'mid-eye to fork of tail']
<bound method Series.unique of 0               108 Creek
1               108 Creek
2               108 Creek
3          18 Mile Slough
4          18 Mile Slough
               ...
16522    Zimovia Straight
16523    Zimovia Straight
16524    Zimovia Straight
16525    Zimovia Straight
16526    Zimovia Straight
Name: locationid, Length: 16527, dtype: object>

In [ ]:
length_type.loc[length_type['length_measurement_type']== 'unknown', 'length_measurement_type'] = np.nan
print(length_type['length_measurement_type'].unique())

['mid-eye to fork of tail' 'length not taken' nan
 'post orbit to fork of tail' 'tip of snout to fork of tail'
 'post orbit to hypural plate' 'mid-eye to hypural plate'
 'tip of snout to tip of tail' 'post-orbit to fork of tail'
 'cleithral arch to fork']

## Clean gear dataframe

In [ ]:
gear.head()

                    Gear             SASAP.Gear
0                    NaN                    NaN
1  handpicked or carcass  handpicked or carcass
2            beach seine                  seine
3    sport hook and line    sport hook and line
4                   weir                   weir

In [ ]:
# clean names 
gear = gear.clean_names()

gear.dropna(inplace=True)

In [ ]:
gear.head()

                    gear             sasap_gear
1  handpicked or carcass  handpicked or carcass
2            beach seine                  seine
3    sport hook and line    sport hook and line
4                   weir                   weir
5          drift gillnet                gillnet

In [ ]:
# save data to a csv file
# gear.to_csv('gear_clean.csv')